### ISSUE TITLE
Improve selection rendering

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-inspector#12]
Do you think that this gif creates the right mental model of how the engine behaves?

![inspector](https://user-images.githubusercontent.com/156149/53735272-b41f4a00-3e86-11e9-901f-332fbc39569c.gif)

To me it looks like the selection which is rendered before applying bold is significantly different than the one rendered after that. Which is not true – it's exactly the same selection with the same properties.

That's why I don't think that the selection should be displayed as if was placed before text nodes.

I'm not sure if this will work but I'd like to see a prototype of something like:

![image](https://user-images.githubusercontent.com/156149/53735486-52abab00-3e87-11e9-896f-533ddce673aa.png)

**Comment by Reinmar** [comment]
For me this ticket is very important because the role of the inspector will be much more significant in creating a mental model of CKEditor 5's internals than everything we'll ever write in the documentation.

**Comment by jodator** [comment]
Another idea for selection rendering. We might use something similar to show selection gravity:
![Peek 2019-04-16 13-48](https://user-images.githubusercontent.com/247363/56270923-91c05380-60f7-11e9-9402-670782f5f534.gif)

**Comment by mlewand** [comment]
That's a nice idea, we'd need to make sure it's understandable for devs without additional docs. Something like a tooltip on hover would be sufficient.
