### ISSUE TITLE
A simple button to get data

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-inspector#121]
Writing `editor.getData()` every time I want to see the data output is annoying. And it gets even worse when the editor is not in the `window` scope and I have to log a DOM element, access `element.ckeditorInstance...` , and so on. I think the right place for global actions is somewhere in the red box

![](https://user-images.githubusercontent.com/1099479/122730245-4b885100-d27a-11eb-9ee3-bc4d610db92e.png)

**Comment by pomek** [comment]
Consider adding an option for visualizing the data pipeline. I mean, showing the editor's data in a `.ck-content` container.

It could even be displayed as a modal.
