### ISSUE TITLE
CkEditor Inspector suddenly stopped working, errors given are meaningless

### ISSUE THREAD

**Issue by Gabriel-rd2** [ckeditor/ckeditor5-inspector#125]
I was working with it normally until it stopped rendering and now i get some unhelpful errors, here is a screenshot of my console:

![Screenshot 2021-09-10 at 16-47-57 Captura de tela de 2021-09-10 16-47-06 png (PNG Image, 1366 × 768 pixels) - Scaled (80%)](https://user-images.githubusercontent.com/85249497/132909435-e58719d1-5787-46c7-ad3e-61e946eb5aec.png)

I am using it with react, attatching the inspector to the editor in the init method of a custom plugin. I am also using a custom build of ckeditor.

**Comment by oleq** [comment]
Could you give us any hint of what was going on in the editor/what did you do in the inspector when this happened? Without this information, this is going to be a tough one to reproduce. Thanks!

**Comment by Gabriel-rd2** [comment]
I was looking at the model to debug a custom element i had defined. I had added a UIElement to my editing View and after deleting the element from the model the editing View was not updated , i changed the inspector's tab to see the view and went to look at my code, changed and saved it, after the yarn hot reload i started getting this error.

**Comment by Gabriel-rd2** [comment]
Update i changed my custom plugin from the react project to the project of a custom build of ckeditor, after that importing and attaching the inspector from the react project works normally!

**Comment by oleq** [comment]
Thanks for the update. I'm closing the issue for now but let's keep an eye on it 👀
