### ISSUE TITLE
Mark UIElements in a special way in the view inspector

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-inspector#13]
We don't control rendering `UIElements` which mean that their DOM element representation (the element itself as well as its children) is not present in the view. So, this means that it will usually look like this sad empty `<div>`:

![image](https://user-images.githubusercontent.com/156149/53760204-7809da80-3ec2-11e9-8069-19cf37981949.png)

It's full of life and content in the DOM, but empty and undefined in the view. We should clearly and distinctively mark it there.

**Comment by oleq** [comment]
Some improvements landed in https://github.com/ckeditor/ckeditor5-inspector/issues/9. But yes, we could make it more distinguishable.
