### ISSUE TITLE
search and replace a word with double spaces is not working.

### ISSUE THREAD

**Issue by karanshaji** [ckeditor/ckeditor5-inspector#131]
search and replace a word with double spaces is not working showing specified word not found.

**Comment by Reinmar** [comment]
I think this was supposed to be a bug report to the editor itself. If it's still occurring please report it on [https://github.com/ckeditor/ckeditor5.](https://github.com/ckeditor/ckeditor5.) Please also provide more details because it's hard to understand what's exactly the issue.
