### ISSUE TITLE
The right pane could be wider

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-inspector#15]
![image](https://user-images.githubusercontent.com/156149/53895507-7d863280-4032-11e9-92ef-ed6e92411247.png)

I think it could be 2x wider. We don't need that much space in the tree view and we need more space in the right view where you'd want to see a bit more of some attr values.

**Comment by msamsel** [comment]
And screen from my side, I also can't see full attribute value here.
![screen shot 2019-03-07 at 15 26 37](https://user-images.githubusercontent.com/9017322/53963395-8425b000-40ed-11e9-84e3-c3e7e87327ce.png)
