### ISSUE TITLE
Why do we have the decoupled editor build inlined in samples?

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-inspector#32]
I'm asking because for https://github.com/ckeditor/ckeditor5/issues/1608#issuecomment-474356539 we need the version of CKE5 with which this inspector version was built (in mind), so if we had cke5-build-decoupled-document in devdeps we could use that.

**Comment by oleq** [comment]
Legacy. I used it to bootstrap the project. Now it can be replaced.
