### ISSUE TITLE
CKEDITOR_INSPECTOR_VERSION didn't update when releasing 1.3.0

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-inspector#36]
It still says it's `CKEDITOR_INSPECTOR_VERSION`. Did you follow https://github.com/ckeditor/ckeditor5-inspector#releasing (the const is set from changelog not from npm), @Reinmar?

If so, we have a bug somewhere.

**Comment by Reinmar** [comment]
Yes, I did follow that. And... I'm quite sure I checked it.

And it's fine:

![image](https://user-images.githubusercontent.com/156149/54949826-36f46b80-4f40-11e9-9556-96b0e7dd6ed1.png)

**Comment by oleq** [comment]
My bad, I used a dev version which wasn't up to date.
