### ISSUE TITLE
Allow destroying (detaching) the inspector 

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-inspector#42]
I was trying to check one thing in our manual tests but I realised that the inspector is affecting the results. It'd be good if it was possible (even via console) to kill it.

![image](https://user-images.githubusercontent.com/156149/55466237-1478e700-55ff-11e9-9ba1-85dc7c36135a.png)

**Comment by oleq** [comment]
You don't want to detach it from an editor instance but to kill the application entirely? Am I getting this right?

**Comment by Reinmar** [comment]
Yes, I want to kill it completely, so it stops affecting the JS execution results.

**Comment by oleq** [comment]
@Reinmar There you go https://github.com/ckeditor/ckeditor5-inspector/pull/46.
