### ISSUE TITLE
Allow to initialize inspector minimalized

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5-inspector#44]
I want to include the inspector in shared codepen listing. It looks nice in pivot orientation:

![image](https://user-images.githubusercontent.com/5353898/55535693-2bc7db00-56b8-11e9-93d7-6b0f7dc0aba0.png)

However most of us use horizontal, 16:9 orientation and this is how it looks like:

![image](https://user-images.githubusercontent.com/5353898/55535502-b78d3780-56b7-11e9-9302-38f5b743aef2.png)

It would be wonderful if I could initialize the inspector minimized.

**Comment by jodator** [comment]
At first I thought that this is controlled by local cache (cookies/local storage) as the inspector remembers previous stat (opened/closed). Unfortunately when opened in porno mode it is opened and it makes sometimes sense to have it closed.
