### ISSUE TITLE
Passing editor to attach() is confusing

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-inspector#48]
ATM you can do 
```js
CKEditorInspector.attach( instance )
CKEditorInspector.attach( 'name', instance )
```

After https://github.com/ckeditor/ckeditor5-inspector/pull/46/files, it will be 
```js
CKEditorInspector.attach( instance, { opts } )
CKEditorInspector.attach( 'name', instance, { opts } )
```

That's a lot of cases to handle and it could be confusing. I'm for changing the API to something simpler, so there are always max 2 arguments:

```js
CKEditorInspector.attach( instance, { opts } )
CKEditorInspector.attach( [ 'name', instance ], { opts } )
```

Or even

```js
CKEditorInspector.attach( instance, { opts } )
CKEditorInspector.attach( { name: instance, otherName: otherInstance }, { opts } )
```

cc @mlewand @Reinmar

**Comment by mlewand** [comment]
@oleq just for me to understand better, why is name required by the inspector in a first place?

**Comment by oleq** [comment]
So when you have 10 editors in a single web page (they could be very similar, having the same content, being empty), you know which one you inspect:

<img width="1440" alt="Screenshot 2019-04-18 at 11 44 31" src="https://user-images.githubusercontent.com/1099479/56352428-893b4c00-61cf-11e9-8f2c-cd5fae06dedd.png">

For instance, you can have a form with 10 fields, each one a different editor.
