### ISSUE TITLE
Implement attachToAll() method using the new editor instance reference API

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-inspector#56]
Thanks https://github.com/ckeditor/ckeditor5-core/pull/184 we can use `domEditableElement.ckeditorInstance` to get the editor instance. `CKEditorInspector.attachToAll()` would do:

```js
const editables = document.querySelectorAll( '.ck-editable' );

for ( editable of editables ) {
    if ( not already attached to editable.ckeditorInstance ) {
        CKEditorInspector.attach( editable.ckeditorInstance );
    }
} 
```

to attach all editor instances automatically. That would be helpful:

* in manual tests, because ATM we only discover `window.editor` and if there is more than a single editor, it's not inspected out-of-the-box. Note that we need a flag like `window.CKEditorInspectorDontAttachAll` so in [some tests](https://github.com/ckeditor/ckeditor5-inspector/issues/52) we can disable this feature.
* in bookmarklets

**Comment by pomek** [comment]
>  Note that we need a flag like window.CKEditorInspectorDontAttachAll so in some tests we can disable this feature.

```js
CKEditorInspector.disableAttachToAll = true
```

or something like that. We don't need to use the global scope for that.

**Comment by oleq** [comment]
It depends on the order of execution. Not sure if `window.CKEditorInspector` namespace would be available at that particular moment when the flag is to be set.

**Comment by pomek** [comment]
You're right, good point. What about element custom attrs (`[data-ckeditor5-inspector="false"]`)?

**Comment by oleq** [comment]
> You're right, good point. What about element custom attrs (`[data-ckeditor5-inspector="false"]`)?

What about the `ClassicEditor`?
