### ISSUE TITLE
Display attributes above properties

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-inspector#6]
I think that attributes are actually more significant because the are what often differentiate nodes:

![image](https://user-images.githubusercontent.com/156149/53578684-61891980-3b78-11e9-92fe-f1a38864e3aa.png)

Properties are always there and you'll be interested in them less often.

**Comment by oleq** [comment]
I tested this approach in the past and it was annoying because depending on the number of attributes (0 to 3 or 4, tops) the list would jump and it's very hard to focus on a single property/attribute while changing nodes in the tree. A poor UX when debugging.
