### ISSUE TITLE
Upgrade dependencies and adjust the code to the latest changes in CKE 5

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5-inspector#61]
I tried to upgrade dependencies defined in the `yarn.lock` file in https://github.com/ckeditor/ckeditor5-inspector/pull/60 but unfortunately, it ends with the duplicated modules error.

I thought that changing numbers in pkg.json will be enough:

```json
{
    "@ckeditor/ckeditor5-basic-styles": "^11.1.4",
    "@ckeditor/ckeditor5-build-decoupled-document": "^12.4.0",
    "@ckeditor/ckeditor5-core": "^12.3.0",
    "@ckeditor/ckeditor5-paragraph": "^11.0.5",
    "@ckeditor/ckeditor5-ui": "^14.0.0",
    "@ckeditor/ckeditor5-utils": "^14.0.0"
}
```

But it's more complicated and after that, 12 tests fail (related to RTL changes) and 50% of the test log is filled by non-related console logs.

**Comment by oleq** [comment]
This has been fixed around here https://github.com/ckeditor/ckeditor5-inspector/pull/46#commits-pushed-08e7077.
