### ISSUE TITLE
Select arrow has invalid styles on Firefox

### ISSUE THREAD

**Issue by elszczepano** [ckeditor/ckeditor5-inspector#65]
## Is this a bug report or feature request?

🐞 Bug report

## 📋 Steps to reproduce

Use the inspector on Firefox. The `select` arrow for e.g. `Editor instance` or `Root` looks slightly different than in Google Chrome:

Chrome:

<img width="1037" alt="Screenshot 2019-10-17 at 14 53 11" src="https://user-images.githubusercontent.com/23155008/67010423-e6b44500-f0ed-11e9-9ffc-a6ccc344cedc.png">

Firefox:

<img width="1031" alt="Screenshot 2019-10-17 at 14 45 51" src="https://user-images.githubusercontent.com/23155008/67010210-86250800-f0ed-11e9-9871-de89cdadd10c.png">

**Comment by elszczepano** [comment]
That's true but it is possible to unify styles for the arrow in every browser.  E.g. try to add `all: unset;` CSS rule on the `<select>` tag in the inspector - the arrow should disappear.

**Comment by mlewand** [comment]
And what OS is used to reproduce the case from the screenshot?

**Comment by elszczepano** [comment]
macOS Catalina 10.15.0

**Comment by jodator** [comment]
> And what OS is used to reproduce the case from the screenshot?

Similar on Linux - it's just a way how browsers render a not-styled select box.
