### ISSUE TITLE
Display all selection ranges

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5-inspector#68]
Currently inspector show only one range from a selection that covers most (if not all) of the possible user selection (on Chrome at least).

There are at least two cases where user can create multi-range selection:

1. When using Firefox
2. Select multiple blocks (via custom plugin)

Current status:

![Peek 2019-11-05 12-03](https://user-images.githubusercontent.com/247363/68202705-7a2db700-ffc4-11e9-8200-99e98a1e2f5f.gif)

As you can see on the gif above I've added the output of the `getModelData()` helper method below the editor.

**Comment by oleq** [comment]
Is there any editor feature that supports this ATM? Because it sounds like an edge case to me.

**Comment by mlewand** [comment]
From what I can tell is that Firefox is currently the only browser that allows you to make multiple selections.

**Comment by jodator** [comment]
@oleq no, but we start working on one: https://github.com/ckeditor/ckeditor5/issues/5684

**Comment by oleq** [comment]
Let's wait for some actual editor feature and develop this in parallel.

**Comment by Reinmar** [comment]
> Let's wait for some actual editor feature and develop this in parallel.

Like table selection? 😂

**Comment by oleq** [comment]
> Like table selection? 😂

Well, yeah. Works for me 😛
