### ISSUE TITLE
Feature request: Show markers

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5-inspector#7]
It would be awesome if the inspector would also show markers. Maybe have a small, scrollable window where you could select (all) / deselect (all) markers you want to display.

I was also thinking about `LiveRange`s and `LivePosition`s. I sometimes need to follow how they change during debugging. However, these are:

1. not named so I am not sure how useful that would be,
2. there's no one place to fetch them from (like `editor.model.markers`).

**Comment by oleq** [comment]
I wanted to implement markers in the MVP but I figured they were hard to display using the tree component I developed for the inspector. If you think this is acceptable to display them like the selection (only `[....]`, nothing in between like the color etc.) then it shouldn't be too much work.

**Comment by scofalik** [comment]
I was thinking like the selection with some indication which marker is which. Either using colors (would fail for more markers) or with a name next to opening and closing bracket (then each bracket would be in a new line).

**Comment by Reinmar** [comment]
I talked with Olek already that the selection could perhaps be displayed in a better way than right now. Perhaps similar to how we display it in the real-time collaboration scenarios. Then we could also display markers.
