### ISSUE TITLE
Inspector could be debounced for performance reasons

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-inspector#71]
I stumbled upon performance issues caused by our dear inspector. When working with a bit longer content, every selection change causes refresh dropping to 20fps. That's due to inspector refresh taking 50ms.

If we could, it'd be great to debounce inspector so it:

* refreshes less often
* does not block the `selectionchange` handler (event)

**Comment by oleq** [comment]
Dup of https://github.com/ckeditor/ckeditor5-inspector/issues/43?
