### ISSUE TITLE
Feature Request: Jump to document selection in inspector

### ISSUE THREAD

**Issue by rshipp** [ckeditor/ckeditor5-inspector#77]
When using the inspector with a large document, it's hard to find things in the model / view tabs. I'd love an option to scroll the inspector view to the current document selection, so I can just click somewhere in the editor, and jump to that location in the inspector.

**Comment by Reinmar** [comment]
That'd be very useful, indeed :+1:

**Comment by oleq** [comment]
Just to let you know, it's on top of my list because this is also bugging me.
