### ISSUE TITLE
Don't render the inspector panes/trees when the inspector is collapsed

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-inspector#80]
ATM even when the inspector is collapsed, it renders all the UI (and first collects data from the editor to do that) which degrades performance when working with large documents.

Fixing this should be fairly simple (around https://github.com/ckeditor/ckeditor5-inspector/blob/396af59ac8e5af038e0772faf2f175e3d9451ee4/src/ckeditorinspector.js#L192-L198 + few store dispatches when the inspector is uncollapsed to stay in sync) and that would help using editor manual test with large content by simply collapsing the inspector.

A follow-up of #79. Related to #71.

**Comment by oskarwrobel** [comment]
This improvement will be very important for documents with markers. Now when there are several markers in the document then performance drop is very noticeable.
