### ISSUE TITLE
react-fast-compare cannot handle circular refs warning in the console

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-inspector#86]
![](https://user-images.githubusercontent.com/1099479/83502947-a4941400-a4c2-11ea-95c4-6db162100530.png)

**Comment by Reinmar** [comment]
I get this warning too. It's pretty annoying. Since @oleq is on :palm\_tree: , does anyone else want to give it a try?

**Comment by FilipTokarski** [comment]
This thing seems to be causing a very long lag/freeze if you do some operations on tables in Safari ( it's not as noticeable in Chrome and FF ). Sometimes I have to wait like 10 seconds before inserting a new column and I get up to hundreds of this warnings at once:  
  
![27_safari2](https://user-images.githubusercontent.com/34380544/88524752-0b810580-cffa-11ea-98a1-0564fc5f4006.gif)
