### ISSUE TITLE
Add toggle inspector shortcut

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5-inspector#87]
This keeps me annoying - I have to use a mouse to toggle the inspector. I would like to have a keyboard shortcut (might be configurable) for that action.

Chrome and Firefox uses <kbd>F12</kbd> to toggle development console. AFAICS the (<kbd>SHFIT</kbd>+) <kbd>ALT</kbd>+<kbd>F12</kbd> isn't used so maybe it would be nice to use that.

As this might interfere with user shortcut maybe a configuration option (on/off only to not make a big deal of that) would be nice too.

**Comment by mlewand** [comment]
@jodator what I can recommend 'till the thing is not out, you can use an extension, like shortkeys (it's available for Chrome and FF) and add a custom hotkey that runs following js:

```
document.querySelector('.ck-inspector-navbox__navigation__toggle ').click()
```

![](https://user-images.githubusercontent.com/5353898/86790069-47aeef00-c068-11ea-9fb0-0ed542ed2401.png)

Just tested it and it works like a charm.

**Comment by jodator** [comment]
@mlewand this plugin doesn't work for me on Firerefox (content orign block scripts on some manual tests)

On chrome:

![](https://user-images.githubusercontent.com/247363/86792556-e9374000-c06a-11ea-9329-6e15c72ed9fc.png)

**Comment by mlewand** [comment]
Oh, that sucks 😟 Been using this extension for ever. Eventually you might want to see if it can be built from sources to test it out https://github.com/mikecrittenden/shortkeys - but yeah… it's a little bit of hassle.

**Comment by oleq** [comment]
@mlewand do you want to propose a PR instead? 😜

*   Methodology: https://stackoverflow.com/a/53033698/1485219
*   Where: https://github.com/ckeditor/ckeditor5-inspector/blob/master/src/ui.js#L38-L100

**Comment by jodator** [comment]
Huh, I can try to do this as I'm most interested in that.

**Comment by oleq** [comment]
It all comes down to executing `toggleIsCollapsed` when the keystroke is pressed. The Redux action is already mapped https://github.com/ckeditor/ckeditor5-inspector/blob/master/src/ui.js#L108 so it should be available in `InspectorUI` as `this.props.toggleIsCollapsed`.

**Comment by oleq** [comment]
Or... the logic could be in `ToggleButtonVisual` since it already handles the same thing when clicked.
