### ISSUE TITLE
[model] Element attributes could be sorted by A-Z

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5-inspector#97]
Sometimes attributes can be set in a different order and it leads to a situation like on the screenshot below:

![image](https://user-images.githubusercontent.com/2270764/89774966-2037c000-db07-11ea-8ed1-a141b48d2d64.png)

![image](https://user-images.githubusercontent.com/2270764/89774977-262da100-db07-11ea-8104-6924ad77d10c.png)

The first and second elements were added after the editor's initialization. The rest was created while initializing the editor during the conversion process. However, I am unsure if the provided information helps enough.

**Comment by oleq** [comment]
Just to be clear, you mean the tree view right?

**Comment by pomek** [comment]
@oleq, yes.

**Comment by oleq** [comment]
Makes sense!
