### ISSUE TITLE
Mention in the initial content throws error

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5-inspector#98]
## Steps to reproduce

1.  Open a sample containing a mention in the initial content (e.g. mentions manual tests).

## Current result

The error is thrown

## Error

```
mathtype.js:75 TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'writer' -> object with constructor 'Writer'
    |     property 'model' -> object with constructor 'Model'
    |     ...
    |     property 'attributes' -> object with constructor 'Object'
    --- property 'mention' closes the circle
    at JSON.stringify (<anonymous>)
    at ce (inspector.js:2)
    at inspector.js:2
    at Array.map (<anonymous>)
    at be (inspector.js:2)
    at inspector.js:2
    at ge (inspector.js:2)
    at inspector.js:2
    at ge (inspector.js:2)
    at inspector.js:2
```

## Notes

It works fine if we load the data without a mention, insert a mention and call `editor.setData( editor.getData() )`.

**Comment by oleq** [comment]
https://github.com/ckeditor/ckeditor5-inspector/blob/master/src/components/utils.js#L15 is the root of the problem. The question remains what data causes this as it gets stringified.
